services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis_data:/data

  ws-server:
    build:
      context: ./ws-server
      dockerfile: Dockerfile
    container_name: ws_server
    working_dir: /app
    volumes:
      - ./ws-server:/app
      - /app/node_modules
    depends_on:
      - redis
    ports:
      - "${WS_SERVER_PORT}:8080"
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
  redis_data:
